### ISSUE TITLE
TypeError: argument 1 must be string, not numpy.ndarray

### ISSUE THREAD

**Issue by elpimous** [alexanderkoumis/opencv-gpu-py#2]
hi Alexander.
Thanks for your nice lib.

Trying to use it in ROS, and here is the problem : 
your lib asks for an image file (like *.jpg)
ros produce a numpy array image !!

Could anyone help me replacing string to array ! (don't anderstand C++,just python)

**Comment by elpimous** [comment]
in face_detector.cpp : 
```
bool FaceDetector::Detect(const char* image_file,
                          std::vector<cv::Rect>& face_rects)
{
  cv::Mat frame = cv::imread(image_file, 0);
  cv::equalizeHist(frame, frame);
```
my ros python produces a an equalizeHist numpy array, so the Detect function should read it directly, but don't know how to do in C

**Comment by elpimous** [comment]
in cv2gpu.cpp : 
```
static PyObject* find_faces(PyObject* self, PyObject* args)
{
  const char* image_path;
  if (init)
  {
    if (PyArg_ParseTuple(args, "s", &image_path))
    {
      std::vector<cv::Rect> face_rects;
      detector.Detect(image_path, face_rects);
```
need to replace const char* image_path;  by the ros numpy array file
Please help

**Comment by alexanderkoumis** [comment]
Hi, I implemented it this way because I'm not too familiar with the C representation of numpy arrays and how to interact with them. I'll leave this issue open in case anyone else has better knowledge of this topic and wants to help out.

**Comment by elpimous** [comment]
Thanks alexanderkoumis

**Comment by alexanderkoumis** [comment]
@elpimous depending on how performance critical your application is, you could write your image to a file and then feed the path to the interface of cv2gpu.

**Comment by alexanderkoumis** [comment]
@elpimous check out this fork, it accomplishes what you want:
https://github.com/tambetm/opencv-gpu-py
I'll probably merge it at some point.

**Comment by elpimous** [comment]
alexanderkoumis,
Thanks a lot !!!! 😀
Impatient to test !!

**Comment by elpimous** [comment]
It works perfectly !!
Thanks Alexander
